apiVersion: v1
kind: ConfigMap
metadata:
  name: flex-gpu-scheduler-config
  namespace: {{ .Values.namespace }}
data:
  scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1beta2
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: false
    profiles:
      - schedulerName: flex-gpu-scheduler
        plugins:
          filter:
            enabled:
            - name: FlexGPU
          score:
            enabled:
            - name: FlexGPU
          reserve:
            enabled:
            - name: FlexGPU
          bind:
            disabled:
            - name: DefaultBinder
            enabled:
            - name: FlexGPU
