apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "flexgpu.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: flex-gpu-scheduler
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flex-gpu-scheduler
subjects:
  - kind: ServiceAccount
    name: {{ include "flexgpu.serviceAccountName" . }}
    namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: flex-gpu-scheduler
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flex-gpu-scheduler-as-kube-scheduler
subjects:
  - kind: ServiceAccount
    name: {{ include "flexgpu.serviceAccountName" . }}
    namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: system:kube-scheduler
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flex-gpu-scheduler-as-volume-scheduler
subjects:
  - kind: ServiceAccount
    name: {{ include "flexgpu.serviceAccountName" . }}
    namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: system:volume-scheduler
  apiGroup: rbac.authorization.k8s.io
